version: '3.8'

services:
  backend:
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile # Dockerfile to use for building the image
    ports:
      - "5000:5000" # Map container port 5000 to host port 5000
    volumes:
      - .:/app # Mount the backend folder to /app in the container
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE=mongodb+srv://vivek:vivek123@cluster0.hzfq07l.mongodb.net/taskapp
      - JWT_SECRET=mysecretkey
    command: npm run dev # Command to run in the container after it's built
